#!/bin/sh -efu

t="${1?}"

run()
{
	echo 'vim:nowrap:nolist:noswapfile:bt=nofile:bh=delete:ft=elvis:'
	vdir -a --time-style='+%Y-%m-%d %H:%M' --group-directories-first "$t" |
	    sed -r \
	      -e "s,^(d[^[:space:]]+[[:space:]]+[0-9]+[[:space:]]+[^[:space:]]+[[:space:]]+[^[:space:]]+[[:space:]]+[0-9]+[[:space:]]+[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}[[:space:]]+)(.*)\$,\1[[exec://$0 $t/\2][\2]]," \
	      -e "s,^(-[^[:space:]]+[[:space:]]+[0-9]+[[:space:]]+[^[:space:]]+[[:space:]]+[^[:space:]]+[[:space:]]+[0-9]+[[:space:]]+[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}[[:space:]]+)(.*)\$,\1[[open://$t/\2][\2]],"
}

if [ -z "${MYVIMRC-}" ]; then
	run |vim -
else
	run
fi
